---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: htpc-nas2
description: A fedora image for i509vcb's combo HTPC and NAS
base-image: ghcr.io/blue-build/base-images/fedora-base
image-version: 43

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # ZFS has to be installed manually with a containerfile.
  #
  # This also replaces the kernel with one compatible with the ZFS module (usually a downgrade).
  - type: containerfile
    containerfiles:
      - zfs

  - type: dnf
    install:
      packages:
        - fastfetch
        - firefox # still has some issues as a flatpak
        - nano
        - steam # still has issues as a flatpak
    group-install:
      packages:
        - kde-desktop
      exclude:
        - krdp
        - krfb

  - type: default-flatpaks
    configurations:
      - scope: system
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          title: Flathub (system)
        install:
          - org.kde.elisa
          - com.usebottles.bottles

  - type: os-release
    properties:
      ID: i5_htpc_nas
      ID_LIKE: fedora
      NAME: i5's HTPC and NAS
      PRETTY_NAME: i5's HTPC and NAS image

  # Enable SDDM service to setup user.
  - type: systemd 
    system:
      enabled:
        - sddm.service

  # The default fedora image goes to multi-user.target. We want the graphical session to start instead.
  - type: script
    snippets:
      - sudo systemctl set-default graphical.target

  # ZFS means we want to always regenerate initramfs (even though I don't run the root fs on ZFS
  - type: initramfs
  - type: signing
